### ISSUE TITLE
Stop the conscan script from being such a piece of shit

### ISSUE THREAD

**Issue by james-see** [jamesacampbell/findpi#7]
This is shit right now:

```
$ sudo python3 conscan.py
Password:
What network do you want to check? (10.2.2.0/24): 192.168.1.0/24
route_dst_generic: Failed to obtain system routes: getsysroutes_dnet: route_loop() failed
Found pi: 192.168.1.232
Traceback (most recent call last):
  File "conscan.py", line 59, in <module>
    main()
  File "conscan.py", line 55, in main
    rs = f.result()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "conscan.py", line 11, in checker
    data = check_output(f"nmap -sP {ip_address}", shell=True)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'nmap -sP 192.168.1.14' returned non-zero exit status 1.
```

**Comment by james-see** [comment]
And the result of running the command manually:

```
Starting Nmap 7.70 ( https://nmap.org ) at 2019-11-12 21:42 EST
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 0.50 seconds
```

**Comment by james-see** [comment]
So it is a non-zero exit code, but we need to either 1. catch this error code properly or we need to stop using the nmap command from within the python library. We are better than that!

**Comment by james-see** [comment]
Fixed and cleaned up!
